api_branch: origin/master
api_parser: ~
api_cfgmod: clone
api_runner: ~
api_paths: lib
env_make: ~
env_prep: composer-get
php_conf: timezone
php_exts: igbinary
app_prep: composer-req
app_post: ~
env_post: composer-del,ci-coveralls,ci-codacy
app_path: ~
pkg_name: arthur-doctrine-identity-library
pkg_desc: "Basic entity classes  for id- slug- uuid-based identities"
pkg_bndl: false
